import Config

# Configure your database
# config :spitegear, Spitegear.Repo,
#   username: "postgres",
#   password: "postgres",
#   hostname: "localhost",
#   database: "spitegear_dev",
#   stacktrace: true,
#   show_sensitive_data_on_connection_error: true,
#   pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :spitegear, SpitegearWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "vdP5k05KTd4i2e5maVkXFKtJ5lO7zESNA+lWMSG+WFPaGbJlyQcuMn3KqxFSlpYm",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:spitegear, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:spitegear, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :spitegear, SpitegearWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/spitegear_web/(controllers|live|components)/.*(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :spitegear, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Include HEEx debug annotations as HTML comments in rendered markup
config :phoenix_live_view, :debug_heex_annotations, true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

config :spitegear, Spitegear.Slack.API,
  url: URI.parse("https://slack.com"),
  channel: "spitegear",
  endpoints: [
    post_message: "/api/chat.postMessage",
    list_channels: "/api/conversations.list",
    read_channel: "/api/conversations.history",
    list_users: "/api/users.list",
    open_conversation: "/api/conversations.open"
  ],
  channel_ids: [
    spitegear: "C014W8DN81X"
  ],
  dm_ids: [
    adam: "D014TFY2K6W"
  ],
  user_ids: [
    adam: "U1LBVMGUU"
  ]
