name: Deploy to Beelink

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy app
    runs-on: self-hosted

    steps:
      - name: Write env file
        run: |
          echo "SLACK_AUTH_TOKEN=${{ secrets.SLACK_AUTH_TOKEN }}" > $HOME/spitegear/.env

      - name: Pull latest code
        run: |
          cd $HOME/spitegear
          git pull origin main

      - name: Build and restart
        run: |
          cd $HOME/spitegear
          make deploy
