name: Deploy to Beelink

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy app
    runs-on: self-hosted
    if: "!contains(github.event.head_commit.message, '[skip deploy]')"

    steps:
      - name: Write env file
        run: |
          cat > $HOME/spitegear/.env << EOF
          SLACK_AUTH_TOKEN=${{ secrets.SLACK_AUTH_TOKEN }}
          SECRET_KEY_BASE=${{ secrets.SECRET_KEY_BASE }}
          DATABASE_URL=ecto://postgres:postgres@postgres/spitegear_dev
          PHX_HOST=spitegear.duckdns.org
          PORT=4001
          PHX_SERVER=true
          WARGEAR_USERNAME=${{ secrets.WARGEAR_USERNAME }}
          WARGEAR_PASSWORD=${{ secrets.WARGEAR_PASSWORD }}
          EOF

      - name: Pull latest code
        run: |
          cd $HOME/spitegear
          git fetch origin main
          git reset --hard origin/main

      - name: Build and restart
        run: |
          cd $HOME/spitegear
          make deploy
